from ucrc.crc8 import crc8
from ucrc.crc8 import crc8_fast
from ucrc.crc8 import crc8_gen_table
from ucrc.crc8_predefines import crc8_sae_j1850
from ucrc.crc8_predefines import crc8_sae_j1850_zero
from ucrc.crc8_predefines import crc8_8h2f
from ucrc.crc8_predefines import crc8_cdma2000
from ucrc.crc8_predefines import crc8_darc
from ucrc.crc8_predefines import crc8_dvb_s2
from ucrc.crc8_predefines import crc8_ebu
from ucrc.crc8_predefines import crc8_icode
from ucrc.crc8_predefines import crc8_itu
from ucrc.crc8_predefines import crc8_maxim
from ucrc.crc8_predefines import crc8_rohc
from ucrc.crc8_predefines import crc8_wcdma

from ucrc.crc16 import crc16
from ucrc.crc16 import crc16_fast
from ucrc.crc16 import crc16_gen_table
from ucrc.crc16_predefines import crc16_ccit_zero
from ucrc.crc16_predefines import crc16_arc
from ucrc.crc16_predefines import crc16_aug_ccitt
from ucrc.crc16_predefines import crc16_buypass
from ucrc.crc16_predefines import crc16_ccitt_false
from ucrc.crc16_predefines import crc16_cdma2000
from ucrc.crc16_predefines import crc16_dds_110
from ucrc.crc16_predefines import crc16_dect_r
from ucrc.crc16_predefines import crc16_dect_x
from ucrc.crc16_predefines import crc16_dnp
from ucrc.crc16_predefines import crc16_en_13757
from ucrc.crc16_predefines import crc16_genibus
from ucrc.crc16_predefines import crc16_maxim
from ucrc.crc16_predefines import crc16_mcrf4xx
from ucrc.crc16_predefines import crc16_riello
from ucrc.crc16_predefines import crc16_t10_dif
from ucrc.crc16_predefines import crc16_teledisk
from ucrc.crc16_predefines import crc16_tms37157
from ucrc.crc16_predefines import crc16_usb
from ucrc.crc16_predefines import crc16_a
from ucrc.crc16_predefines import crc16_kermit
from ucrc.crc16_predefines import crc16_modbus
from ucrc.crc16_predefines import crc16_x_25
from ucrc.crc16_predefines import crc16_xmodem

from ucrc.crc32 import crc32
from ucrc.crc32 import crc32_fast
from ucrc.crc32 import crc32_gen_table
from ucrc.crc32_predefines import crc32_bzip2
from ucrc.crc32_predefines import crc32_c
from ucrc.crc32_predefines import crc32_d
from ucrc.crc32_predefines import crc32_mpeg2
from ucrc.crc32_predefines import crc32_posix
from ucrc.crc32_predefines import crc32_q
from ucrc.crc32_predefines import crc32_jamcrc
from ucrc.crc32_predefines import crc32_xfer

from ucrc.crc64 import crc64