from ucrc.crc8 import crc8
from ucrc.crc8 import crc8_fast
from ucrc.crc8 import crc8_gen_table
from ucrc.crc16 import crc16
from ucrc.crc16 import crc16_fast
from ucrc.crc16 import crc16_gen_table
from ucrc.crc32 import crc32
from ucrc.crc32 import crc32_fast
from ucrc.crc32 import crc32_gen_table